Update beginner tutorial: Change front end, suggestions for localhost running, reformat tutorial
workfloworchestrator/orchestrator-core pull request #733
Opened 2024-08-12 21:25 UTC by Justin-Zwart

This PR was created to change a number of outdated features in the beginner tutorial, and add some clarity.

New features:
 - mention an easy way to run backend without auth in on localhost
 - update links to point to the correct location in the documentation
 - merge "overview" and "scenario" into one cohesive file explaining all the top-down approach
 - update `debian.md` and `start_applications.md` files to work with `orchestrator-ui` instead of `orchestrator_core_gui`

Continued work before this PR is ready to submit:
- there is no explanation for how to set up the orchestrator-ui in macos, as I do not have the ability to set up / test
- the dockerfile in the associated beginner orchestrator and the docker tutorial have not been updated to use the orchestrator-ui, as I have been running my setups manually.

2024-09-09 13:16 UTC, pboers1988 requested changes
Pre-commit (linting) is failing

2024-09-18 22:51 UTC, Justin-Zwart commented
> @Justin-Zwart Thanks for the contribution. If you don't mind could you make sure it gets through pre-commit? Then we can accept.

Hi Peter,

I am happy to update the linting in the next couple of days. I have been super busy with the start of my school term. I also need someone other than myself to make progress on some of the code which I am not able to complete myself. I mention this in the description of the PR. For example I am not updating the docker and haven't tested it on Mac.

2024-10-07 09:18 UTC, pboers1988 approved these changes

2024-10-07 09:19 UTC, pboers1988 commented
Thanks LGTM

2024-10-07 09:19 UTC, merged